### ISSUE TITLE
UML state diagram 

### ISSUE THREAD

**Issue by kavova199** [TIS2020-FMFI/skodovy-protokol#20]

**Comment by kavova199** [comment]
Prvá verzia UML state diagramu 
![UMLstate1](https://user-images.githubusercontent.com/29478285/98610750-9e675680-22f0-11eb-9af6-98dab30ff978.png)

**Comment by kavova199** [comment]
Opravený state diagram
@pavelpetrovic 
![Untitled Diagram](https://user-images.githubusercontent.com/29478285/100007630-9fa68200-2dcc-11eb-92a2-914fc5bef65d.png)

**Comment by kavova199** [comment]
Aktualizovaný state diagram používateľského rozhrania @pavelpetrovic  
![state2](https://user-images.githubusercontent.com/29478285/100680624-385f7380-3372-11eb-8edb-1f7762d8cd7c.png)

**Comment by kavova199** [comment]
Aktualizovaný state diagram používateľského rozhrania. @pavelpetrovic 

![statef](https://user-images.githubusercontent.com/29478285/101410539-cc37bf00-38df-11eb-845a-4d7c6cdbadd2.jpg)

**Comment by pavelpetrovic** [comment]
a to je aká entita? používateľské rozhranie?
tam by som skôr očakával stavy ako "je zobrazená stránka na prihlásenie používateľa", alebo "je zobrazená stránka na zadanie výrobného čísla auta" atď.

**Comment by kavova199** [comment]
Používateľské rozhranie. @pavelpetrovic 
![stat999](https://user-images.githubusercontent.com/29478285/102402787-92547000-3fe5-11eb-8b65-465279d2082c.jpg)

**Comment by kavova199** [comment]
Používateľské rozhranie. @pavelpetrovic 
![stm](https://user-images.githubusercontent.com/29478285/102539320-d01ccb80-40ad-11eb-8c5d-1dc12b430dfc.jpg)

**Comment by kavova199** [comment]
![stat2](https://user-images.githubusercontent.com/29478285/106371243-59d4df80-6362-11eb-87c4-2e728f33360d.png)
