### ISSUE TITLE
UML class diagram

### ISSUE THREAD

**Issue by kavova199** [TIS2020-FMFI/skodovy-protokol#22]

**Comment by MartinKristak** [comment]
![project-class](https://user-images.githubusercontent.com/71854595/100739188-02a0a600-33d7-11eb-8855-3177a2724c84.png)

**Comment by MartinKristak** [comment]
![class-editingProtocol](https://user-images.githubusercontent.com/71854595/100918115-5cd56000-34d8-11eb-89b9-a2dc36e79700.png)
![class_email](https://user-images.githubusercontent.com/71854595/100918119-5e9f2380-34d8-11eb-810f-8c27b20fdd25.png)

@pavelpetrovic ,  ako ste navrhovali na stretnutí, pridal som nový diagram znázorňujúci sťahovanie .csv z mailov. K triede Car som pridal triedu CarFinder, ktorej úlohou je hľadať autá v DB.  Mohli by ste prosím pridať koment, či je to OK? Ďakujem

**Comment by pavelpetrovic** [comment]
ten findCarsByOrderID teda nepotrebujeme a tym padom staci dat tu metodu findCarByVIN() asi priamo do triedy Car

**Comment by MartinKristak** [comment]
![class-email](https://user-images.githubusercontent.com/71854595/100920803-ed616f80-34db-11eb-9bd7-d88ca937433c.png)
![class_editingProtocol](https://user-images.githubusercontent.com/71854595/100920807-ee929c80-34db-11eb-956d-0884c955c1a8.png)
