### ISSUE TITLE
Návrh používateľského rozhrania GUI

### ISSUE THREAD

**Issue by kavova199** [TIS2020-FMFI/skodovy-protokol#23]

**Comment by MartinKristak** [comment]
https://drive.google.com/file/d/1VsmGwxl4H9M9AWOtFmDWm1L0jBhlffQz/view?usp=sharing

**Comment by Villiss** [comment]
GUI:
https://app.moqups.com/VDhnHoEywt/edit/page/ab8341126

**Comment by Villiss** [comment]
https://app.moqups.com/VDhnHoEywt/edit/page/ab8341126
@pavelpetrovic 
GUI

**Comment by Villiss** [comment]
https://app.moqups.com/VDhnHoEywt/edit/page/ab8341126

Pridaný náhľad fotografií podľa dohody + pridaný náhľad výsledného .pdf súboru podľa KP  a TS. Myslím, že by to mohla byť finálna verzia. Prípadné dizajnové "vychytávky" budem riešiť na podnet zadávateľa.

@pavelpetrovic
