### ISSUE TITLE
Use-case diagram

### ISSUE THREAD

**Issue by MartinKristak** [TIS2020-FMFI/skodovy-protokol#25]

**Comment by MartinKristak** [comment]
![use-case](https://user-images.githubusercontent.com/71854595/98992353-626d0500-252d-11eb-8c5a-9d415d2c314f.png)

**Comment by MartinKristak** [comment]
@pavelpetrovic

**Comment by pavelpetrovic** [comment]
ok.
v piatok som hovoril s Gefco, zda sa, ze predsa len sa budu protokoly nahravat na sharepoint, slubili, ze coskoro dodaju pristup k testovaciemu sharepointu, kde to mozete otestovat. skuste, prosim, preskumat technologie, pomocou ktorych moze aplikacia nieco na sharepoint nahrat.
