### ISSUE TITLE
Testovacie scenáre

### ISSUE THREAD

**Issue by Villiss** [TIS2020-FMFI/skodovy-protokol#27]

**Comment by MartinKristak** [comment]
zdieľaný dokument: 

https://docs.google.com/document/d/1MgTtqDVnxaFt6Kl9YN23WT2dWCHftwkEL3OG19kb3X0/edit?usp=sharing

**Comment by Villiss** [comment]
Testovacie scenáre
@pavelpetrovic

**Comment by pavelpetrovic** [comment]
zatiaľ to vyzerá fajn, skontrolujte ako to pokrýva KP
