### ISSUE TITLE
Tvorba katalógu požiadaviek 

### ISSUE THREAD

**Issue by GreathKhans** [TIS2020-FMFI/skodovy-protokol#4]

**Comment by MartinKristak** [comment]
Odkaz pre zdielaný dokument: https://docs.google.com/document/d/1s6UV8xJjg681_Y7hnpllpX0czOitgqdRrx7pz4OBLA8/edit?usp=sharing

**Comment by kavova199** [comment]
[Katalóg požiadaviek.docx](https://github.com/TIS2020-FMFI/skodovy-protokol/files/5389783/Katalog.poziadaviek.docx)

Čakáme na schválenie zadávateľom.

@pavelpetrovic

**Comment by pavelpetrovic** [comment]
Ďakujem za vypracovanie prvej verzie katalógu požiadaviek. Ide to správnym smerom. Ako som už avizoval, predtým, ako KP pošlete zadávateľom na schválenie, je potrebné, aby s ním bol spokojný cvičiaci. Prikladám novú verziu s mojimi komentármi (zapol som v dokumente trackovanie zmien). Prosím zapracujte ich podľa situácie a Vašich poznatkov o požiadavkách, ak treba doplniť informácie od zadávateľov, kontaktujte ich. Keď bude výsledok upravený, prosím ešte raz mi ho pošlite na rýchlu výslednú kontrolu predtým, ako ho pošlete zadávateľom. Ďakujem.
[Katalog_poziadaviek_s_komentarmi.docx](https://github.com/TIS2020-FMFI/skodovy-protokol/files/5398447/Katalog_poziadaviek_s_komentarmi.docx)

**Comment by kavova199** [comment]
Opravený katalóg požiadaviek. 

@pavelpetrovic  

[Katalóg_požiadaviek.docx](https://github.com/TIS2020-FMFI/skodovy-protokol/files/5431476/Katalog_poziadaviek.docx)

**Comment by pavelpetrovic** [comment]
Dakujem za aktualizaciu KP. Urobil som tam par drobnych uprav (je zapnute trackovanie zmien, takze ich uvidite), doplnil som par komentarov, prosim dokladne ich zapracujte a potom este dajte jednu notifikaciu, sem s vysledkom, ale zaroven ho poslite zadavatelom a poziadajte ich, aby si dokument dokladne prestudovali a dali Vam k nemu spatnu vazbu, ci tam este nieco netreba zmenit, alebo ci ho schvaluju, lebo ked ho schvalia, tak podla toho system naprogramujete.
Hovoril som s technikom kratko minuly tyzden, vravel, ze ten mailovy ucet bude u nich a maju tam softver MS Exchange. Pytal som sa, ze ci sa tam daju pridat nejake skripty, ktore by prichadzajuce spravy hned spracovali a ulozili do databazy automaticky, on nevedel, ale povedal, ze ked to tak pripravite, tak to bude ok. Na internete sa zda byt viacero odkazov, podla ktorych by to malo ist, tak si aspon niekto nainstalujte exchange a vyskusajte, prosim, ci vhodnu technologiu skriptov do exchange najdete.
[katalogPoziadaviekEdit_s_komentarmi.docx](https://github.com/TIS2020-FMFI/skodovy-protokol/files/5442179/katalogPoziadaviekEdit_s_komentarmi.docx)

**Comment by Villiss** [comment]
> Dakujem za aktualizaciu KP. Urobil som tam par drobnych uprav (je zapnute trackovanie zmien, takze ich uvidite), doplnil som par komentarov, prosim dokladne ich zapracujte a potom este dajte jednu notifikaciu, sem s vysledkom, ale zaroven ho poslite zadavatelom a poziadajte ich, aby si dokument dokladne prestudovali a dali Vam k nemu spatnu vazbu, ci tam este nieco netreba zmenit, alebo ci ho schvaluju, lebo ked ho schvalia, tak podla toho system naprogramujete.
> Hovoril som s technikom kratko minuly tyzden, vravel, ze ten mailovy ucet bude u nich a maju tam softver MS Exchange. Pytal som sa, ze ci sa tam daju pridat nejake skripty, ktore by prichadzajuce spravy hned spracovali a ulozili do databazy automaticky, on nevedel, ale povedal, ze ked to tak pripravite, tak to bude ok. Na internete sa zda byt viacero odkazov, podla ktorych by to malo ist, tak si aspon niekto nainstalujte exchange a vyskusajte, prosim, ci vhodnu technologiu skriptov do exchange najdete.
> [katalogPoziadaviekEdit_s_komentarmi.docx](https://github.com/TIS2020-FMFI/skodovy-protokol/files/5442179/katalogPoziadaviekEdit_s_komentarmi.docx)

Dobrý deň, ďakujeme, avšak obávam sa, že ste nám poslali Katalóg inej skupiny.
@pavelpetrovic

**Comment by pavelpetrovic** [comment]
pravda! :)
napravujem!
[Katalog_poziadaviek_s_komentarmi.docx](https://github.com/TIS2020-FMFI/skodovy-protokol/files/5443724/Katalog_poziadaviek_s_komentarmi.docx)

**Comment by kavova199** [comment]
[Katalóg požiadviek (1).docx](https://github.com/TIS2020-FMFI/skodovy-protokol/files/5467232/Katalog.poziadviek.1.docx)

Aktualizovaný katalóg požiadaviek. 

@pavelpetrovic

**Comment by kavova199** [comment]
Stále čakáme na odpovede od zadávateľa ohľadom nejasností zadania projektu. Odpovede sú potrebné k úplnému dokončeniu katalógu požiadaviek.

**Comment by kavova199** [comment]
Opravený katalóg požiadaviek. 

@pavelpetrovic 
[Katalóg požiadviek (2).docx](https://github.com/TIS2020-FMFI/skodovy-protokol/files/5541416/Katalog.poziadviek.2.docx)

**Comment by pavelpetrovic** [comment]
Ďakujem pekne za aktualizáciu KP. 

* v 2.2, 2.4 a 2.5 píšete, že na vstupe bude XLSX, určite to nebude CSV? Myslím, že posielali obidva, ale neviem, ktorý je platný, či oba, alebo iba jeden, Vám je to jasné, prečo tam boli aj CSV aj XLSX?
* v 2.2. a 2.5 píšete, že na výstupe bude .txt alebo .csv, ale podľa toho, čo ste mi hovorili, že generujete škodový protokol, ktorý má aj nejaké formátovanie to nesedí. V súboroch .txt a .csv žiadne formátovanie nevyrobíte. 
* veta 2.5 "Spracovanie mailov z pridelenej e-mailovej adresy by malo byť realizované skriptom, resp. iným vhodným spôsobom z mailového programu MS Exchange. "  ten Exchange padol. Navrhujem to nahradiť: "pomocou protokolu IMAP z mailového servera, ktorého konfigurácia sa zadá do konfiguračného súboru."
(k tomu len poznámka, ktorá nemá dopad na KP: podľa mňa by teda na servri bežal nejaký samostatný program, ktorý by sa tam automaticky spustil po nabootovaní a ktorý by sa do mailovej schránky díval povedzme každú minútu. toto môžete napísať aj v hociakom inom jazyku, napr. v jave - na to nájdete na nete dosť príkladov)
* prosím upresniť formuláciu v 3.1.5: "Po zvolení typu škodového protokolu" - nie je jasné, čo sa tým myslí, treba to rozviesť podrobnejšie - znamená to len určenie protokolu podľa značky? To sa neurčí automaticky - bude to treba voliť? Alebo to znamená rôzne protokoly aj pre jednu značku? Rozpíšte to, prosím, podrobnejšie.
* ešte by sa tam niekde malo objaviť, že tie informácie v škodovom protokole, ktoré sa dajú vyplniť automaticky z informácií, ktoré prišli v zozname objednávok mailom, sa tam vložia automaticky (aspoň tak som pochopil, že by sa to malo udiať).
* o tom výstupnom formáte protokolu (napr. PDF) by sa mala objaviť informácia aj niekde v 3. časti KP. 
(poznámka: ak budete generovať PDF, tak by ste mohli skúsiť tak, že na strane klienta sa len zobrazí HTML v ktorom sa povypĺňajú hodnoty a na strane servra sa vygeneruje také isté HTML, ktoré sa skonvertuje do PDF - také konvertory existujú a určite nájdete, napr. tu https://github.com/dompdf/dompdf alebo aj iné...)

Inak je to krásne, tak to už len prosím v týchto bodoch dotiahnite a potom pošlite na opripomienkovanie všetkým stakeholderom z Gefco (pošlite mi kópiu). Vďaka!

**Comment by pavelpetrovic** [comment]
od pani Tryznovej som dostal tuto informaciu:

V prvom maili je vzor reportu z nasho systemu vo formate csv : tento bude sluzit ako vstup pre projekt SP
Avsak data v tomto subore je potrebne zmenit data aby vyhovovali poziadavkam projektu + treba nastavit cielovu mailovu adresu kam sa bude posielat
Ake data sa do reportu daju nastavit, o tom hovori druhy mail s prilohou xlsx
Ked to zhrniem: format reportu bude csv, ale policka v reporte budu zodpovedat vzoru xlsx
 
cize csv a este na vystupe by bolo asi najlepsie pdf (?)

**Comment by pavelpetrovic** [comment]
prišla odpoveď od p. Fagulu:

Dobry den,

ano chapete to spravne. Automaticky mail je generovany v CSV, pricom jednotlive policka v reporte si mozete zadefinovat podla XLSX.
Ak chcete mat presne tie policka, ktore som poslal, vieme to tak dat nastavit.

pekny den prajem

Peter FAGULA

**Comment by kavova199** [comment]
Opravený katalóg požiadaviek.  @pavelpetrovic    
[Katalóg požiadviek (3).docx](https://github.com/TIS2020-FMFI/skodovy-protokol/files/5609218/Katalog.poziadviek.3.docx)

**Comment by pavelpetrovic** [comment]
Dobrý deň, ďakujem, prečítal som si to. Mám ešte jeden problem:
Na odkaze, kde máte ponahrávané tie protokoly sa vyskytujú zvlášť protokoly pre vozidlo a zvlášť pre diely.
V KP o tom nič nevidím. Vypĺňajú sa oba, alebo vždy iba jeden? Ako sa zistí ktorý? Alebo je to tak, že keď sa vezie celé auto, vypĺňa sa o aute a keď sa vezú samostatné diely, tak sa vypĺňa o dieloch? Budete mať vo vstupe dosť informácií, aby ste vedeli určiť, ktorý sa má použiť? V každom prípade o tomto musí v KP byť zmienka. Vyriešte, prosím, ešte tento problém a upravte podľa toho KP a potom požiadajte zadávateľov, aby si ho dôkladne prečítali a odpísali Vám, či to takto môže byť. Ak ste s nimi ešte nemali hovor ohľadne návrhu používateľského rozhrania, môžete si dohodnúť predbežne termín na ten hovor.

**Comment by kavova199** [comment]
Nová verzia katalógu požiadaviek. @pavelpetrovic  
[Katalóg požiadviek (4).docx](https://github.com/TIS2020-FMFI/skodovy-protokol/files/5622617/Katalog.poziadviek.4.docx)

**Comment by pavelpetrovic** [comment]
Dobrý deň, mal som dnes hovor s Gefco kvôli druhému projektu, ale opýtal som sa ich na tie otázky, ktoré mi boli trochu nejasné, tu sú závery:
 - vyhľadanie vozidla stačí podľa výrobného čísla, netreba to podľa dátumu objednávky, takže len jedným spôsobom
 - tak ako sme diskutovali o tých zoznamoch dielov - do exportovaných protokolov stačí prvá strana, netreba nič prekladať, ale na stránke by bolo dobré, aby sa dali zobraziť tie kódy dielov (napr. v susednom TABe) - aby keď to pracovník vypĺňa, tak sa mohol pozrieť do zoznamu kódov
 - maily s údajmi budú chodiť denne
 - aké staré záznamy sa majú mazať z databázy by mohol byť napr. tých 7 dní, ale tak, aby sa to dalo ľahko zmeniť niekde v konfigu zo 7 napr. na 14.

Bolo by super, ak by sa Vám podarilo dať zadávateľom prototyp na testovanie niekedy pred Vianocami.

**Comment by kavova199** [comment]
Finálna verzia katalógu požiadaviek. @pavelpetrovic   
[Katalóg požiadviek (5).docx](https://github.com/TIS2020-FMFI/skodovy-protokol/files/5649318/Katalog.poziadviek.5.docx)

**Comment by kavova199** [comment]
Čaká sa na schválenie zadávateľom.
