### ISSUE TITLE
Finálna dokumentácia

### ISSUE THREAD

**Issue by kavova199** [TIS2020-FMFI/skodovy-protokol#68]

**Comment by kavova199** [comment]
@pavelpetrovic 
[dokumentaciafinal.docx](https://github.com/TIS2020-FMFI/skodovy-protokol/files/5901291/dokumentaciafinal.docx)

**Comment by pavelpetrovic** [comment]
v dokumentacii zatial nevidim nic o technologiach, ktore pouzivate na nahravanie na sharepoint a tiez tych, co pouzivate na vytahovanie z mailu. chybaju tam informacie o perzistentnej vrstve - model databazy, kde ukladate informacie vytiahnute z mailov.
potrebujem aj komunikacny protokol medzi frontendom a backendom a ku kazdemu komponentu z komponentneho diagramu napisat zo dve vety aku ma v aplikacii zodpovednost. 

nezabudnite potom, ked to bude cele fungovat, vyrobit aj 3-minutove videjko, kde poviete aky problem ste isli riesit, ake technologicke vyzvy ste museli zvladnut a ako to napokon vyzera (v tej ukazke prosim ukazte potom aj ten sharepoint adresar so zip-om, ktory to nahra a vyplnte nejaky cely protokol -mozete pozastavit nahravanie, povyplnat a potom zasa spustit nahravanie ako je uz vyplneny, aby to nebolo zbytocne dlhe).

teraz sa ale cely tim zamerajte, prosim, hlavne na to, aby aplikacia uz zacala cela fungovat.

dakujem.

**Comment by kavova199** [comment]
Aktualizovaná verzia. @pavelpetrovic 
[dokumentaciafinal.docx](https://github.com/TIS2020-FMFI/skodovy-protokol/files/5946310/dokumentaciafinal.docx)
