### ISSUE TITLE
Vymyslieť ako budeme vyberať údaje z mailu pre ďalšiu prácu

### ISSUE THREAD

**Issue by Villiss** [TIS2020-FMFI/skodovy-protokol#9]

**Comment by pavelpetrovic** [comment]
snažil som sa zistiť viac o tej možnosti vytvoriť skripty v MS Exchange, ale môj predbežný záver je, že bude lepšie, keď sa to spraví naopak: program sa sám bude pomocou POP3 (alebo radšej IMAP4) pozerať do schránky a vyťahovať odtiaľ správy - napr. raz za minútu. To by znamenalo, že by ste urobili program, ktorý by stále bežal na ich servri (v hociakom jazyku), ktorý by sa každú minútu pozrel do schránky a vytiahol odtial všetky nové maily, spracoval ich a informácie zaradil do databázy.

Iný spôsob by bol, že by sa to automaticky udialo vtedy, keď si niekto stránku otvorí a ešte aj na nejaké tlačidlo 
[znovu načítať objednávky].

Nevýhodou druhého prístupu by bolo, že to pripájanie do schránky, vyťahovanie mailov z nej, všetko trvá pár sekúnd,
takže by to mohlo zdržovať. PHP má zabudovanú podporu pre prístup do mailovej schránky cez IMAP:
https://www.php.net/manual/en/function.imap-open.php

Nevýhodou prvého prístupu by bolo, že sa musí vyvinúť a nainštalovať samostatný program, tak, aby po spustení stále bežal na ich servri, čo by podľa mňa ale nemal byť žiaden zásadný problém. IMAP API nájdete pre všetky bežné jazyky, napr:
https://www.oracle.com/java/technologies/javamail.html
https://docs.python.org/3/library/imaplib.html

IMAP je podporované aj bežnými internetnetovými mailovými servrami ako gmail a podobne, takže by sa to asi dalo testovať aj na nich, predtým ako bude schránka priamo na ich servri.
